import Foundation

/// Raw image data as read from the pasteboard, before normalisation.
public struct PasteboardImage: Equatable, Sendable {
    public var data: Data
    /// Uniform type identifier of `data`, e.g. "public.png" or "public.tiff".
    public var typeIdentifier: String

    public init(data: Data, typeIdentifier: String) {
        self.data = data
        self.typeIdentifier = typeIdentifier
    }
}

/// Content Clipstack writes back to the system clipboard.
public enum PasteboardWrite: Equatable, Sendable {
    case text(String)
    case pngImage(Data)
}

public enum PasteboardWriteError: Error, Equatable {
    case rejected
}

/// Abstraction over the system pasteboard so capture logic can be tested without AppKit.
///
/// Reading is split into steps so the capture policy can decide *before* any content is
/// read (for example while paused, or when the source app is excluded).
public protocol PasteboardSource: AnyObject {
    /// Increments whenever the clipboard's owner changes (mirrors `NSPasteboard.changeCount`).
    var changeCount: Int { get }
    /// Type identifiers currently on the pasteboard. Reading types does not read content.
    func currentTypes() -> [String]
    func readText() -> String?
    func readImage() -> PasteboardImage?
    /// Replaces the clipboard contents and returns the resulting change count.
    func write(_ content: PasteboardWrite) throws -> Int
}

/// The application that most likely owns a clipboard change.
public struct SourceApp: Equatable, Sendable {
    public var bundleID: String?
    public var name: String?

    public init(bundleID: String?, name: String?) {
        self.bundleID = bundleID
        self.name = name
    }
}

/// Supplies the app to attribute a clipboard change to (on macOS: the frontmost app).
public protocol SourceAppProvider: AnyObject {
    func currentSourceApp() -> SourceApp?
}

/// Pasteboard type identifiers the capture policy cares about.
public enum PasteboardTypes {
    /// Markers from the nspasteboard.org convention. Password managers and similar apps
    /// add these to say "do not record this". Clipstack always honours them.
    public static let privacyMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
    ]

    /// File copies (e.g. from Finder) are not supported in this version. Finder also places
    /// the file name as text and the file icon as an image, which would be misleading to store.
    public static let fileURL = "public.file-url"
    public static let legacyFilenames = "NSFilenamesPboardType"

    public static func containsPrivacyMarker(_ types: [String]) -> Bool {
        types.contains { privacyMarkers.contains($0) }
    }

    public static func containsFiles(_ types: [String]) -> Bool {
        types.contains { $0 == fileURL || $0 == legacyFilenames }
    }
}
