import XCTest
@testable import ClipstackCore

@MainActor
final class PauseTests: XCTestCase {
    func testNothingIsReadOrCapturedWhilePaused() async {
        let h = Harness()
        h.history.setPaused(true)
        h.pasteboard.copyText("secret")

        XCTAssertEqual(h.history.poll(), .paused)
        XCTAssertEqual(h.pasteboard.contentReads, 0, "content must not be read while paused")
        XCTAssertTrue(h.history.items.isEmpty)
        XCTAssertTrue(h.files(in: "Images").isEmpty)
    }

    func testResumingDoesNotCaptureWhatWasCopiedWhilePaused() async {
        let h = Harness()
        h.history.setPaused(true)
        h.pasteboard.copyText("copied while paused")
        h.history.setPaused(false)

        XCTAssertEqual(h.history.poll(), .unchanged)
        XCTAssertTrue(h.history.items.isEmpty)

        h.pasteboard.copyText("after resume")
        guard case .captured(let item) = h.history.poll() else { return XCTFail("expected capture") }
        XCTAssertEqual(item.text, "after resume")
    }

    func testResumingBeforeAPollAlsoSkipsPausedCopy() async {
        // The pause window can be shorter than the polling interval.
        let h = Harness()
        h.history.setPaused(true)
        h.pasteboard.copyText("quick")
        h.history.setPaused(false)
        XCTAssertEqual(h.history.poll(), .unchanged)
    }

    func testPauseStatePersistsAcrossLaunches() async {
        let h = Harness()
        h.history.setPaused(true)
        h.relaunch()
        XCTAssertTrue(h.history.settings.isPaused)
        h.pasteboard.copyText("secret")
        XCTAssertEqual(h.history.poll(), .paused)
    }

    func testPausedImagesAreNotProcessed() async {
        let h = Harness()
        h.history.setPaused(true)
        h.pasteboard.copyImage(Data([1]))
        XCTAssertEqual(h.history.poll(), .paused)
        XCTAssertEqual(h.images.processCount, 0)
    }
}

@MainActor
final class ExclusionTests: XCTestCase {
    func testExcludedAppIsNotCapturedAndContentIsNotRead() async {
        let h = Harness()
        h.history.updateSettings { $0.addExclusion("com.example.Vault") }
        h.apps.current = SourceApp(bundleID: "com.example.Vault", name: "Vault")
        h.pasteboard.copyText("hunter2")

        XCTAssertEqual(h.history.poll(), .excluded(bundleID: "com.example.Vault"))
        XCTAssertEqual(h.pasteboard.contentReads, 0)
        XCTAssertTrue(h.history.items.isEmpty)
    }

    func testExclusionMatchIsCaseInsensitive() async {
        let h = Harness()
        h.history.updateSettings { $0.addExclusion("com.Example.vault") }
        h.apps.current = SourceApp(bundleID: "COM.EXAMPLE.VAULT", name: "Vault")
        h.pasteboard.copyText("x")
        XCTAssertEqual(h.history.poll(), .excluded(bundleID: "COM.EXAMPLE.VAULT"))
    }

    func testOtherAppsAreStillCaptured() async {
        let h = Harness()
        h.history.updateSettings { $0.addExclusion("com.example.Vault") }
        h.apps.current = SourceApp(bundleID: "com.example.Notes", name: "Notes")
        h.pasteboard.copyText("shopping list")
        guard case .captured = h.history.poll() else { return XCTFail("expected capture") }
    }

    func testRemovingAnExclusionResumesCaptureForThatApp() async {
        let h = Harness()
        h.history.updateSettings { $0.addExclusion("com.example.Vault") }
        h.history.updateSettings { $0.removeExclusion("com.example.vault") }
        h.apps.current = SourceApp(bundleID: "com.example.Vault", name: "Vault")
        h.pasteboard.copyText("x")
        guard case .captured = h.history.poll() else { return XCTFail("expected capture") }
    }

    func testDefaultExclusionsCoverPasswordManagers() async {
        let h = Harness()
        h.apps.current = SourceApp(bundleID: "com.1password.1password", name: "1Password")
        h.pasteboard.copyText("password")
        XCTAssertEqual(h.history.poll(), .excluded(bundleID: "com.1password.1password"))
    }

    func testConcealedPasteboardTypesAreNeverCaptured() async {
        let h = Harness()
        h.history.updateSettings { $0.excludedBundleIDs = [] }
        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType"] {
            h.pasteboard.copyText("secret", extraTypes: [marker])
            XCTAssertEqual(h.history.poll(), .concealed)
        }
        XCTAssertEqual(h.pasteboard.contentReads, 0)
        XCTAssertTrue(h.history.items.isEmpty)
    }

    func testAddExclusionValidatesInput() async {
        var settings = ClipstackSettings(excludedBundleIDs: [])
        XCTAssertTrue(settings.addExclusion("  com.example.App \n"))
        XCTAssertEqual(settings.excludedBundleIDs, ["com.example.App"])
        XCTAssertFalse(settings.addExclusion("COM.EXAMPLE.APP"), "duplicates are rejected")
        XCTAssertFalse(settings.addExclusion(""))
        XCTAssertFalse(settings.addExclusion("not a bundle id"))
        XCTAssertEqual(settings.excludedBundleIDs.count, 1)
    }

    func testExclusionsPersist() async {
        let h = Harness()
        h.history.updateSettings { $0.addExclusion("com.example.Vault") }
        h.relaunch()
        XCTAssertTrue(h.history.settings.isExcluded(bundleID: "com.example.Vault"))
    }
}
